### ISSUE TITLE
[Feature request] Have right/left click in pen mode perform different actions

### ISSUE THREAD

**Issue by distek** [ryrun/com.dufte.SimplePianoroll.xrnx#4]
Hello!

This is amazing, thank you for doing all this!

I was thinking to more emulate the way the FL piano roll works (should probably be toggle-able):
- Left click in pen mode draws note if grid cell is empty, and lets one move the note if the cell is not empty
- Right click deletes note under cursor, or multiple notes if dragged.

I tried playing around with the code last night, but there doesn't seem to be a way to really detect if right click occurred. Currently, it seems that if _any_ click happened, it sets `leftClick` to true.

If you don't want to pursue this, totally cool. Just a thought I had.

Thanks again for this.

**Comment by ryrun** [comment]
Thank you. I'll add an option for pen mode mouse move instead of remove. Right click is currently not possible. The button notifiers do not distinguish between left and right mouse button. So its currently a Renoise API limit. Maybe in future :)

**Comment by distek** [comment]
Ah, okay! If right click isn't accessible, then I don't know if there's much of a point to that option. Similar could be achieved with just holding alt. Maybe hold alt to delete as well? Basically inverting the current functionality.

Thanks!

**Comment by ryrun** [comment]
I've uploaded 3.1 which allow you to move notes in pen mode. There is now an option:
![image](https://user-images.githubusercontent.com/1203821/156428006-8e060d5d-2863-4b23-872e-4ae9d75eea6a.png)

Right click will be added, when the api have functions to distinguish between left and right button. I'll close this case for now, but i've your request on my todo.
