### ISSUE TITLE
[Linux] mouse cursor position reset after click

### ISSUE THREAD

**Issue by defensem3ch** [ryrun/com.dufte.SimplePianoroll.xrnx#5]
using on Linux Mint 20.3 the mouse cursor position always resets to lower left corner on click

**Comment by ryrun** [comment]
Hi, you need to turn of mouse warping in Renoise. The tool is using the XYPad trick to get mouse positions. Its currently the only way. I hope the dev's will add an option for that, so it can be disabled per control. In the coming version, there will be a mouse warping compatibility mode, with some downsides like disabled selection marker and so on.

**Comment by defensem3ch** [comment]
where can i turn off mouse warping? sorry don't know what that is or where
to find it

**Comment by ryrun** [comment]
@defensem3ch You can find it in the GUI section: 
![image](https://user-images.githubusercontent.com/1203821/155030953-04d7c0c6-fad1-46a7-a9c3-9714a335cad0.png)

**Comment by defensem3ch** [comment]
thank you!

**Comment by ryrun** [comment]
I've uploaded version 3.1, which have a mouse warping compatibility mode. So no more jumping, when the general option is enabled and needed. As far as i know, Renoise 3.4 will improve the handling of mouse warping abit better.
![image](https://user-images.githubusercontent.com/1203821/156427361-fe8fd4b4-ac2c-4784-bd63-ab2d9767e4d1.png)
