### ISSUE TITLE
Set the Piano-Roll Screen too large. Now I can not reach the preference button to switch back to smaller screen

### ISSUE THREAD

**Issue by Malu007** [ryrun/com.dufte.SimplePianoroll.xrnx#6]
Sure I can move the window even if it is too large. But not vertically :)
Is there a trick to reset the window size or to move it vertically?

**Comment by ryrun** [comment]
Hi. Oh, good find. I've uploaded a new test build where you can use ctrl+p to open the preferences. This should help you.
See https://github.com/ryrun/com.dufte.SimplePianoroll.xrnx/tree/master/out

Does this help you?

**Comment by ryrun** [comment]
I'll close the case. There are currently two ways to reach the preferences for your situation. I hope it helps you.

**Comment by Malu007** [comment]
Thank you! Both ways work.
